import logging
from fastapi import APIRouter, Depends, WebSocket, WebSocketDisconnect
from langchain_core.messages import HumanMessage

from app.api.deps import get_current_active_user
from app.database.session import get_db, async_session_maker
from app.models.user import User
from app.schemas.chat import ChatMessageRequest, ChatMessageResponse
from app.services.ai.agent import agent_app
from app.core.security import decode_token
from app.repositories.user import UserRepository
from app.core.websocket_manager import manager

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("/message", response_model=ChatMessageResponse)
async def send_message(
    chat_in: ChatMessageRequest,
    current_user: User = Depends(get_current_active_user),
    db=Depends(get_db)
):
    """
    Send a customer support query message.
    Triage routes the query via LangGraph state machine, performing RAG search
    or human agent escalation depending on user message content.
    """
    # 1. Initialize LangGraph starting state
    initial_state = {
        "messages": [HumanMessage(content=chat_in.message)],
        "routing_target": "general",
        "routing_reason": "",
        "rag_context": "",
        "response": "",
        "db": db,
        "user_id": current_user.id
    }
    
    # 2. Invoke the compiled LangGraph Agent state machine asynchronously
    result = await agent_app.ainvoke(initial_state)
    
    return {
        "response": result.get("response", "No response generated by agent."),
        "routing_target": result.get("routing_target", "general"),
        "routing_reason": result.get("routing_reason", "No triaging logic completed."),
    }


@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    WebSocket endpoint for real-time customer support chat and ticketing notifications.
    Supports token authentication via first payload frame.
    """
    await websocket.accept()
    user = None
    try:
        # Expect first frame to contain: {"token": "access_token"}
        auth_data = await websocket.receive_json()
        token = auth_data.get("token")
        if not token:
            await websocket.send_json({"type": "error", "message": "Missing authentication token."})
            await websocket.close(code=1008)
            return

        async with async_session_maker() as db:
            try:
                payload = decode_token(token)
                if payload.get("type") != "access":
                    await websocket.send_json({"type": "error", "message": "Invalid token type."})
                    await websocket.close(code=1008)
                    return
                user_id = int(payload.get("sub"))
                user_repo = UserRepository(db)
                user = await user_repo.get(user_id)
                if not user or not user.is_active:
                    await websocket.send_json({"type": "error", "message": "Authentication failed: user inactive."})
                    await websocket.close(code=1008)
                    return
            except Exception as e:
                logger.error(f"WebSocket auth exception: {e}")
                await websocket.send_json({"type": "error", "message": "Authentication failed."})
                await websocket.close(code=1008)
                return

        # Handshake success: register connection in ConnectionManager
        await manager.connect(websocket, user.id, user.role)
        await websocket.send_json({
            "type": "auth_ok",
            "user": {
                "id": user.id,
                "email": user.email,
                "role": user.role
            }
        })

        # Main message processing loop
        while True:
            data = await websocket.receive_json()
            msg_type = data.get("type")

            if msg_type == "chat_message":
                content = data.get("message", "").strip()
                if not content:
                    continue

                try:
                    # Run LangGraph flow asynchronously in database context
                    async with async_session_maker() as db:
                        initial_state = {
                            "messages": [HumanMessage(content=content)],
                            "routing_target": "general",
                            "routing_reason": "",
                            "rag_context": "",
                            "response": "",
                            "db": db,
                            "user_id": user.id
                        }
                        
                        result = await agent_app.ainvoke(initial_state)
                        response_text = result.get("response", "No response generated by agent.")
                        routing_target = result.get("routing_target", "general")
                        routing_reason = result.get("routing_reason", "No triaging logic completed.")

                        # Reply to sender
                        await websocket.send_json({
                            "type": "chat_response",
                            "response": response_text,
                            "routing_target": routing_target,
                            "routing_reason": routing_reason
                        })

                        # If ticket escalated, broadcast new ticket alert to agents and admins
                        if routing_target == "escalate":
                            from app.repositories.ticket import TicketRepository
                            ticket_repo = TicketRepository(db)
                            tickets = await ticket_repo.get_all_by_user(user.id)
                            latest_ticket = tickets[-1] if tickets else None
                            
                            if latest_ticket:
                                await manager.broadcast_to_roles({
                                    "type": "new_ticket_alert",
                                    "ticket": {
                                        "id": latest_ticket.id,
                                        "subject": latest_ticket.subject,
                                        "priority": latest_ticket.priority,
                                        "status": latest_ticket.status,
                                        "user_id": latest_ticket.user_id,
                                        "created_at": latest_ticket.created_at.isoformat()
                                    }
                                }, roles=["agent", "admin"])
                except Exception as e:
                    logger.error(f"Error invoking agent over WebSocket: {e}")
                    await websocket.send_json({
                        "type": "chat_response",
                        "response": f"Sorry, I encountered an error: {str(e)}. Please check your backend environment configuration (such as the GEMINI_API_KEY).",
                        "routing_target": "general",
                        "routing_reason": "error_fallback"
                    })

    except WebSocketDisconnect:
        if user:
            manager.disconnect(websocket)
    except Exception as e:
        logger.error(f"WebSocket execution error: {e}")
        if user:
            manager.disconnect(websocket)

