from fastapi import APIRouter, Depends
from langchain_core.messages import HumanMessage

from app.api.deps import get_current_active_user
from app.models.user import User
from app.schemas.chat import ChatMessageRequest, ChatMessageResponse
from app.services.ai.agent import agent_app

router = APIRouter()


@router.post("/message", response_model=ChatMessageResponse)
async def send_message(
    chat_in: ChatMessageRequest,
    current_user: User = Depends(get_current_active_user)
):
    """
    Send a customer support query message.
    Triage routes the query via LangGraph state machine, performing RAG search
    or human agent escalation depending on user message content.
    """
    # 1. Initialize LangGraph starting state
    initial_state = {
        "messages": [HumanMessage(content=chat_in.message)],
        "routing_target": "general",
        "routing_reason": "",
        "rag_context": "",
        "response": "",
    }
    
    # 2. Invoke the compiled LangGraph Agent state machine asynchronously
    result = await agent_app.ainvoke(initial_state)
    
    return {
        "response": result.get("response", "No response generated by agent."),
        "routing_target": result.get("routing_target", "general"),
        "routing_reason": result.get("routing_reason", "No triaging logic completed."),
    }
